export const SEARCH_FOCUS="SEARCH_FOCUS";
export const SEARCH_BLUR="SEARCH_BLUR";
export const CHANGE_LIST="CHANGE_LIST";
export const CHANGE_MOUSEIN="CHANGE_MOUSEIN";
export const CHANGE_MOUSELEAVE="CHANGE_MOUSELEAVE";
export const CHANGE_PAGE="CHANGE_PAGE";